---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
      - name: test-container
        image: gcr.io/agwe-2/web:latest
        ports:
        - containerPort: 80
      