---
apiVersion: v1
kind: Service
metadata:
  name: image-deployment
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: image